$('.shelf.a').mousedown(function(){
	$('.case').css({'grid-template-columns':'50% 1fr 1fr 1fr 1fr 1fr'});
	$('.title.a').css({'font-family':'University','font-size':'5rem','line-height':'4rem','text-transform':'uppercase'})
	// $('.subtitle.a').css({'font-size':'4rem'})
	$('.title.b').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.c').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.d').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.e').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.f').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
})

$('.shelf.b').mousedown(function(){
	$('.case').css({'grid-template-columns':'1fr 50% 1fr 1fr 1fr 1fr'})
	$('.title.a').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.b').css({'font-family':'University','font-size':'5rem','line-height':'4rem','text-transform':'uppercase'})
	// $('.subtitle.b').css({'font-size':'4rem'})
	$('.title.c').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.d').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.e').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.f').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
})

$('.shelf.c').mousedown(function(){
	$('.case').css({'grid-template-columns':'1fr 1fr 50% 1fr 1fr 1fr'})
	$('.title.a').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.b').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.c').css({'font-family':'University','font-size':'5rem','line-height':'4rem','text-transform':'uppercase'})
	// $('.subtitle.c').css({'font-size':'4rem'})
	$('.title.d').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.e').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.f').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
})

$('.shelf.d').mousedown(function(){
	$('.case').css({'grid-template-columns':'1fr 1fr 1fr 50% 1fr 1fr'})
	$('.title.a').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.b').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.c').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.d').css({'font-family':'University','font-size':'5rem','line-height':'4rem','text-transform':'uppercase'})
	// $('.subtitle.d').css({'font-size':'4rem'})
	$('.title.e').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.f').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
})

$('.shelf.e').mousedown(function(){
	$('.case').css({'grid-template-columns':'1fr 1fr 1fr 1fr 50% 1fr'})
	$('.title.a').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.b').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.c').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.d').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.e').css({'font-family':'University','font-size':'5rem','line-height':'4rem','text-transform':'uppercase'})
	// $('.subtitle.e').css({'font-size':'4rem'})
	$('.title.f').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
})

$('.shelf.f').mousedown(function(){
	$('.case').css({'grid-template-columns':'1fr 1fr 1fr 1fr 1fr 50%'})
	$('.title.a').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.b').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.c').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.d').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.e').css({'font-family':'Canela','font-size':'1rem','line-height':'100%','text-transform':'capitalize'})
	$('.title.f').css({'font-family':'University','font-size':'5rem','line-height':'4rem','text-transform':'uppercase'})
	// $('.subtitle.f').css({'font-size':'4rem'})
})