$('.shelf.a').mousedown(function(){
	$('.case').css({'grid-template-columns':'4rem 50% 1fr 1fr 1fr 1fr 1fr 4rem'});
	$('.title.a').css({'font-family':'Ribes','font-size':'4rem','line-height':'4rem','margin-top':'1rem','text-transform':'uppercase'})	
	// $('.title.a').addClass('.title-clicked')
	// $('.subtitle.a').css({'font-size':'4rem'})
	$('.title.b').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.c').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.d').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.e').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.f').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
})

$('.shelf.b').mousedown(function(){
	$('.case').css({'grid-template-columns':'4rem 1fr 50% 1fr 1fr 1fr 1fr 4rem'})
	$('.title.a').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.b').css({'font-family':'Ribes','font-size':'4rem','line-height':'4rem','margin-top':'1rem','text-transform':'uppercase'})
	// $('.subtitle.b').css({'font-size':'4rem'})
	$('.title.c').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.d').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.e').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.f').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
})

$('.shelf.c').mousedown(function(){
	$('.case').css({'grid-template-columns':'4rem 1fr 1fr 50% 1fr 1fr 1fr 4rem'})
	$('.title.a').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.b').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.c').css({'font-family':'Ribes','font-size':'4rem','line-height':'4rem','margin-top':'1rem','text-transform':'uppercase'})
	// $('.subtitle.c').css({'font-size':'4rem'})
	$('.title.d').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.e').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.f').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
})

$('.shelf.d').mousedown(function(){
	$('.case').css({'grid-template-columns':'4rem 1fr 1fr 1fr 50% 1fr 1fr 4rem'})
	$('.title.a').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.b').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.c').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.d').css({'font-family':'Ribes','font-size':'4rem','line-height':'4rem','margin-top':'1rem','text-transform':'uppercase'})
	// $('.subtitle.d').css({'font-size':'4rem'})
	$('.title.e').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.f').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
})

$('.shelf.e').mousedown(function(){
	$('.case').css({'grid-template-columns':'4rem 1fr 1fr 1fr 1fr 50% 1fr 4rem'})
	$('.title.a').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.b').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.c').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.d').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.e').css({'font-family':'Ribes','font-size':'4rem','line-height':'4rem','margin-top':'1rem','text-transform':'uppercase'})
	// $('.subtitle.e').css({'font-size':'4rem'})
	$('.title.f').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
})

$('.shelf.f').mousedown(function(){
	$('.case').css({'grid-template-columns':'4rem 1fr 1fr 1fr 1fr 1fr 50% 4rem'})
	$('.title.a').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.b').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.c').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.d').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.e').css({'font-family':'Basis','font-size':'1rem','line-height':'1rem','margin-top':'0rem','text-transform':'capitalize'})
	$('.title.f').css({'font-family':'Ribes','font-size':'4rem','line-height':'4rem','margin-top':'1rem','text-transform':'uppercase'})
	// $('.subtitle.f').css({'font-size':'4rem'})
})